Analyzer/urls.py
from django.conf.urls import url
from . import views

app_name = 'Analyzer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^status/$', views.process, name='process'),
    url(r'^(?P<offset>[0-9]+)/coordinates/$', views.get_coordinates, name='get_coordinates'),
    url(r'^dashboard/$', views.load_data, name='load_data'),
]

Twitter_Analytics_App/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Analyzer/', include('Analyzer.urls')),
]

Analyzer/forms.py
from django import forms


class TopicForm(forms.Form):
    topic = forms.CharField(max_length=128)

Analyzer/views.py
import logging
from django.http import HttpResponse
from django.shortcuts import render
from kafka import KafkaConsumer
from kafka import TopicPartition
from Analyzer.forms import TopicForm
from .twitter_handler import TwitterAccess

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def index(request):
    form = TopicForm(request.POST)
    return render(request, 'Analyzer/topic.html', {'form': form})


# Create your views here.
def process(request):
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            search_topic = form.cleaned_data['topic']
            TwitterAccess.get_stream(search_topic)
            return render(request, 'Analyzer/index.html')
    else:
        return HttpResponse("Only POST is supported")

    return HttpResponse("Error")


def get_coordinates(request, offset):
    consumer = KafkaConsumer()
    topic_partition = TopicPartition('Python', 0)
    consumer.assign([topic_partition])
    consumer.seek(partition=topic_partition, offset=int(offset))
    data = {}
    while not data:
        data = consumer.poll(timeout_ms=0, max_records=1)
    location = ''
    logger.debug(data)
    for k, v in data.items():
        location = str(v[0].value, 'utf-8')

    return HttpResponse(location)


def load_data(request):
    return render(request, 'Analyzer/dashboard.html')

Analyzer/templates/Analyzer/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'client_app/getPoints.js' %}" ></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Kafka-Python Django app</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'client_app/bootstrap-3.3.7/bootstrap-3.3.7/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    
    <!-- Custom styles for this template -->
    <link href="{% static 'client_app/cover.css' %}" rel="stylesheet">
    <style>
        #map {
        height: 500px;
        width: 1000px;
        position: absolute;
        right: 24%;
        top: 10%;
        }
    </style>
    <script>
        function initMap() {
            var location = {lat: 34, lng: 27};
                map = new google.maps.Map(document.getElementById('map'), {
                zoom: 2,
                center: location
                });
        }
        function startSearch(){
            start(map);
        }
    </script>

   
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">
        <div id="map"></div>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCwHyc7aGvkDL7xfIxsXnH5E9sWFC9e7nM&callback=initMap">
        </script>

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"></h3>
              <nav>
                <ul class="nav masthead-nav">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Analytics</a></li>
                  <li><a href="#">Contact</a></li>
                </ul>
              </nav>
            </div>
          </div>
    
            
    
          <div class="inner cover">

            <h1 class="cover-heading">Twitter-Kafka Consumer</h1>
            <p class="lead">Press Start to start tracking tweets!</p>
            <p class="lead">
              <button type="button" onclick="startSearch()" class="btn btn-lg btn-default" id="startButton" value = "start">
              Start
              <span id="startIcon" class="glyphicon glyphicon-ok-sign" ></span>
              </button>
            </p>
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>A Ben Peters app, powered by Django and <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'client_app/bootstrap-3.3.7/bootstrap-3.3.7/dist/js/bootstrap.min.js' %}"></script>
    
  </body>
</html>

Analyzer/templates/Analyzer/topic.html
<!DOCTYPE html>
<html>
    <head>
        <title>Kafka - Twitter App</title>
    </head>

    <body>
        <h1>Kafka - Twitter App</h1>
        <h3>Enter a search term</h3>

        <form id="topic_form" method="post" action="{% url 'Analyzer:process' %}">

            {% csrf_token %}


            {% for field in form.visible_fields %}
                {{ field }}
            {% endfor %}

            <input type="submit" name="Create Topic" value="Create Topic" />
        </form>
    </body>

</html>